defmodule Daakia.Repo.Migrations.AddedUniqueEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscribers) do
      modify :email, :citext
    end

    create unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")

    alter table(:subscribers) do
      modify :email, :text
    end
  end
end