defmodule Daakia.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:subscribers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :text, null: false
      add :name, :text
      add :attributes, :map, null: false, default: %{}
      add :status, :text, null: false, default: "enabled"
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:subscriber_lists, primary_key: false) do
      add :status, :text, null: false
      add :meta, :map, null: false, default: %{}
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :subscriber_id,
          references(:subscribers,
            column: :id,
            name: "subscriber_lists_subscriber_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :list_id, :uuid, null: false, primary_key: true
    end

    create table(:lists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:subscriber_lists) do
      modify :list_id,
             references(:lists,
               column: :id,
               name: "subscriber_lists_list_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:lists) do
      add :name, :text, null: false
      add :description, :text
      add :type, :text, null: false
      add :optin, :text, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :owner_id,
          references(:users,
            column: :id,
            name: "lists_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:campaigns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :subject, :text, null: false
      add :from_email, :text, null: false
      add :body, :text, null: false
      add :altbody, :text
      add :content_type, :text, null: false, default: "richtext"
      add :send_at, :utc_datetime
      add :headers, :map, null: false, default: %{}
      add :status, :text, null: false, default: "draft"
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "campaigns_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:campaigns, "campaigns_user_id_fkey")

    drop table(:campaigns)

    drop constraint(:lists, "lists_owner_id_fkey")

    alter table(:lists) do
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :optin
      remove :type
      remove :description
      remove :name
    end

    drop constraint(:subscriber_lists, "subscriber_lists_list_id_fkey")

    alter table(:subscriber_lists) do
      modify :list_id, :uuid
    end

    drop table(:lists)

    drop constraint(:subscriber_lists, "subscriber_lists_subscriber_id_fkey")

    drop table(:subscriber_lists)

    drop table(:subscribers)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end